### ISSUE TITLE
Automatically detect input for inside builds

### ISSUE THREAD

**Issue by bkabrda** [DBuildService/atomic-reactor#189]
It should be possible to detect input automatically for inside builds. I think we can create an input plugin that would be triggered on `--input auto` (and will also be the default), that will decide which input to use. Users will still be able to explicitly select different input method if they need to do that for some reason.

**Comment by bkabrda** [comment]
An idea: what if we added a mandatory method to `InputPlugin` subclasses, like `is_autousable`, which would return `True` if the plugin is usable and `False` if not (is usable == an env variable is defined/a file is in a certain path/whatever the plugin needs to work).
Dock would then run this method on all input plugins and start a build only if this method would return `True` on exactly one input plugin, otherwise fail and ask for explicit user input.

Thoughts? @TomasTomecek @mmilata @twaugh

**Comment by mmilata** [comment]
Sounds alright to me, because this would allow one docker image to be used both with and without OSBS. Not sure how this fits into #85, though.

**Comment by TomasTomecek** [comment]
> `is_autousable`

...sounds really good! I like it.
