### ISSUE TITLE
Creating guidelines for contributing

### ISSUE THREAD

**Issue by bkabrda** [DBuildService/atomic-reactor#196]
I'd like to create a `CONTRIBUTING.md` document to state out some rules for PR authors and reviewers. My initial ideas are:

- maximum line length is 100 chars (we don't have this right now, but we can fix that in time and we can only accept PRs that adhere to this from now on)
- there must be no pep8/pyflakes errors unless there's a compelling reason to break these (which is very rare)
- methods that are to be called by different parts of code (i.e. public methods and functions) must have docstrings
- code must be "readable" - meaning:
  - comments where needed
  - separating logical parts of functions by a newline
  - meaningful variable names
- landscape.io test must come out clean
- travis tests must pass
- new features must have user documentation
- new features must have tests (at least a basic smoketest)

What else? Let's brainstorm! Once we have a complete list and approval from all current comitters, I'll create the contribution guidelines and send them as a PR.

**Comment by TomasTomecek** [comment]
I knew you will do this :)

I agree with every point.

My suggestions:

 * all non trivial changes should go through PRs and should NOT be merged by patch author
  * trivial change -- obvious oneliner/bug, typo, docs/packaging fixup
 * I would be even in favor of hooking this repo to coveralls and deny every patch which decreases coverage

**Comment by bkabrda** [comment]
Agreed with both points. I'd still love to hear comments from @jpopelka and @twaugh

**Comment by jpopelka** [comment]
> maximum line length is 100 chars

Some (like [Google](http://google.github.io/styleguide/pyguide.html?showone=Line_length#Line_length)) prefer [80](http://stackoverflow.com/questions/578059/studies-on-optimal-code-width) and for example [PyCharm](https://www.jetbrains.com/pycharm/) defaults to 120. So why 100 ?

> there must be no pep8/pyflakes errors unless there's a compelling reason to break these (which is very rare)
> landscape.io test must come out clean

These two seem the same to me as landscape.io runs pylint which AFAIK checks for PEP-8. No idea if there's any automated way to run pyflakes.

My suggestions:
* A significant improvement should be documented as a GitHub issue before anybody starts working on it.
* Pull requests must be cleanly rebased on top of master without multiple branches mixed into the PR.

**Comment by bkabrda** [comment]
> maximum line length is 100 chars
> 
> Some (like Google) prefer 80 and for example PyCharm defaults to 120. So why 100 ?

Pep 8 has been modified some time ago to mention that 100 chars per line is acceptable: https://www.python.org/dev/peps/pep-0008/#maximum-line-length

>     there must be no pep8/pyflakes errors unless there's a compelling reason to break these (which is very rare)
>     landscape.io test must come out clean
> 
> These two seem the same to me as landscape.io runs pylint which AFAIK checks for PEP-8. No idea if there's any automated way to run pyflakes.

I think that pylint is *subset* of what landscape does [1]. So maybe this should be rephrased as something like "landscape test must come out clean. To check your code locally, use pylint, pyflakes and pep8."

> My suggestions:
> 
>     A significant improvement should be documented as a GitHub issue before anybody starts working on it.
>     Pull requests must be cleanly rebased on top of master without multiple branches mixed into the PR.

+1 to both points

[1] https://docs.landscape.io/configuration.html

**Comment by TomasTomecek** [comment]
> Pull requests must be cleanly rebased on top of master without multiple branches mixed into the PR.

big plus one to this; I would love to have clean history and everything [FF](http://ariya.ofilabs.com/2013/09/fast-forward-git-merge.html)

**Comment by twaugh** [comment]
> big plus one to this; I would love to have clean history and everything FF

On that subject, did you know you can track PRs from `refs/remotes/origin/pr/*`? Then you can fast-forward merge even with remote PRs.

**Comment by jpopelka** [comment]
> I would be even in favor of hooking this repo to coveralls and deny every patch which decreases coverage

Then I'm [doomed](https://github.com/DBuildService/atomic-reactor/pull/201#issuecomment-117205387) ;-)

**Comment by twaugh** [comment]
I'm not so sold on having everything fast-forward, myself.

I definitely think we want to enforce the landscape checks.

**Comment by twaugh** [comment]
Having experience of how coveralls works now, I'm not sure how much sense it makes to enforce no decrease in coverage. It gives false positives, and even when it has useful things to say it doesn't say them very clearly. I guess we can leave it in `CONTRIBUTING.md` but be able to override it on a case-by-case basis.

**Comment by TomasTomecek** [comment]
My point mainly was: write code which has tests :)

**Comment by twaugh** [comment]
Yes, strongly agreed.

**Comment by bkabrda** [comment]
I added one more commit to #204 which explicitly states that coveralls test passing is a soft requirement because of false positives. Hopefully everything is ok now and it can be merged.
