### ISSUE TITLE
Resolve dependency on python-simplejson

### ISSUE THREAD

**Issue by mmilata** [DBuildService/atomic-reactor#207]
Used by pulp_push plugin.

**Comment by TomasTomecek** [comment]
dockpulp should have such dependency, doesn't it?

**Comment by bkabrda** [comment]
Why doesn't it use the builtin `json` module?

**Comment by TomasTomecek** [comment]
python 2.6

**Comment by bkabrda** [comment]
Ah, right. Then I'll just recommend to add it in setup.py conditionally, based on `sys.version_info`, not to unnecessarily install it on newer Python versions.

**Comment by twaugh** [comment]
Let's be clear: the `push_pulp` plugin doesn't use `simplejson` or `json`, it just uses

**Comment by bkabrda** [comment]
But it seems that `json` module is also used in different places:

```bash
[bkabrda@dhcp-30-110 atomic-reactor]$ grep -r json | grep import
tests/plugins/test_add_labels.py:import json
tests/test_plugin.py:import json
atomic_reactor/plugins/input_osv3.py:import json
atomic_reactor/plugins/pre_add_labels_in_df.py:import json
atomic_reactor/plugins/input_path.py:import json
atomic_reactor/plugins/post_store_logs_to_file.py:import json
atomic_reactor/plugins/input_env.py:import json
atomic_reactor/plugins/post_store_metadata_in_osv3.py:import json
atomic_reactor/util.py:import json
atomic_reactor/cli/secret.py:import json
atomic_reactor/cli/main.py:import json
atomic_reactor/outer.py:import json
atomic_reactor/inner.py:import json
atomic_reactor/core.py:import json
```

So I think we should add the dependency for Python 2.6 anyway.

**Comment by twaugh** [comment]
Those all work fine on Python 2.6 without `simplejson`: https://travis-ci.org/DBuildService/atomic-reactor/jobs/69363935

It's only the `push_pulp` plugin (skipped in the above test) that fails, and that's because `dockpulp` imports `simplejson` (unconditionally).

**Comment by bkabrda** [comment]
Ok, so I'm a bit confused here. Python added `json` in 2.6 [1], not in 2.7 as I thought previously. So why can't push_pulp just use that? @TomasTomecek why is "python 2.6" a reason for depending on simplejson?

[1] https://docs.python.org/2/library/json.html

**Comment by TomasTomecek** [comment]
Aha, didn't know that. I really thought that on 2.6 you need to go for simplejson. Therefore I suggest bring this at dockpulp upstream.

**Comment by twaugh** [comment]
https://github.com/release-engineering/dockpulp/pull/12
