### ISSUE TITLE
RFE: read Architecture LABEL from image defined in FROM and define that LABEL for current one too

### ISSUE THREAD

**Issue by pbabinca** [DBuildService/atomic-reactor#212]
Base image has Architecture LABEL which can be reused in child layered images. This request is to inherit Architecture LABELs.

Proposed changes to atomic-reactor:
1. in the part where atomic-reactor rewrites FROM directive to ID of the image read LABEL of the image and save it for future use
2. in the part where Dockerfile is read check if LABEL is defined. If it isn't write new LABEL to the Dockerfile with the value from parent. If value of the Architecture differs fail the build (at the moment. unless we find some proper justification for having two different values as valid use case).
3. after the build return Architecture LABEL as part of the response

If LABEL wasn't present in the Dockerfile and was added later it should be possible to query this label in any child so the process above would work transparently for them too.

Related issue: https://github.com/release-engineering/koji-containerbuild/issues/3

Snippet of docker inspect on base image:
```
    [{
        "Architecture": "amd64",
        "Config": {
            "Labels": {
                "Architecture": "x86_64",
…
            },
```

**Comment by TomasTomecek** [comment]
Sounds good to me. It really is a bit much to redefine `Architecture` since most of the time it's included in base image.

We should probably store stuff from `docker inspect` in build metadata. Not sure if just labels, or whole json.

**Comment by TomasTomecek** [comment]
Looks like that `insert labels` plugin should get some context:
 1. `architecture` should be inherited from base image (what about other labels?)
 2. `N`, `V`, `R` labels got to be overwritten

Therefore the plugin should have some rules for updating labels: `N`, `V`, `R` needs to be overwritten, rest may be overwritten (but needs to be present)
